apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - name: drupal
        image: drupal:8.7.7
        envFrom:
        - secretRef:
            name: postgres-secret
        env:
        - name: POSTGRES_HOST
          value: postgres
        ports:
        - containerPort: 80
