apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
      - name: remove-lost-found
        image: busybox
        command: ["rm", "-rf", "/var/lib/postgresql/data/pgdata/lost+found"]
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data/pgdata
      containers:
      - name: postgres
        image: postgres:11.5
        envFrom:
        - secretRef:
            name: postgres-secret
        - configMapRef:
            name: postgres-config
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data/pgdata
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc-new
